apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: wisecow
  labels:
    app: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: katsura11/wisecow:latest    # locally built image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4499
        # Optional: readiness probe to check container is alive
        readinessProbe:
          exec:
            command:
              - nc
              - -z
              - localhost
              - "4499"
          initialDelaySeconds: 2
          periodSeconds: 5
