name: Wisecow CI/CD (Build → Push → Deploy)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/wisecow

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (supports multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (latest + sha)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Output pushed image
        run: |
          echo "Pushed images:"
          echo "${{ env.IMAGE_NAME }}:latest"
          echo "${{ env.IMAGE_NAME }}:${{ github.sha }}"

  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Setup kubeconfig from secret
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Set image to new sha tag
      run: |
        kubectl -n wisecow set image deployment/wisecow-deployment wisecow=${{ env.IMAGE_NAME }}:${{ github.sha }} --record

    - name: Wait for rollout to finish
      run: |
        kubectl -n wisecow rollout status deployment/wisecow-deployment --timeout=180s
